get http://localhost:3000/players/



###
GET http://localhost:3000/players/1/

###
GET http://localhost:3000/matches/2/

###
PUT http://localhost:3000/players/2/
Content-Type: application/json 

{
    "PlayerName":"Raju"
}


###

get http://localhost:3000/players/2/matches/  

###

get http://localhost:3000/matches/2/players/

###

get http://localhost:3000/players/3/playerScores/